"""
PDF Generation Tool — generates a formatted PDF and returns a downloadable file attachment.
Uses reportlab for lightweight PDF rendering.
"""
import os
import time
import json
from pathlib import Path
from langchain_core.tools import tool
from pydantic import BaseModel, Field

# Output directory for generated PDFs (reuse uploads dir from config)
try:
    from config import DATA_DIR
    PDF_DIR = DATA_DIR / "pdfs"
except Exception:
    PDF_DIR = Path(__file__).resolve().parent.parent / "data" / "pdfs"

PDF_DIR.mkdir(parents=True, exist_ok=True)


import logging

logger = logging.getLogger(__name__)

class PdfInput(BaseModel):
    title: str = Field(description="The title of the PDF document.")
    content: str = Field(description="The main body content/text of the PDF.")


@tool("generate_pdf", args_schema=PdfInput)
def generate_pdf(title: str, content: str) -> str:
    """
    Generate a downloadable PDF document with the given title and content.
    Use this tool when the user asks to export, download, save, or generate a PDF of some content,
    or specifically asks for output "in a pdf format", "as a PDF", "make a PDF", or "convert to PDF".
    Returns a JSON payload with a download URL for the frontend to render as a file card.
    """
    logger.info(f"Generating PDF with title: '{title}', content length: {len(content)}")
    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.units import cm
        from reportlab.lib.colors import HexColor
        from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, HRFlowable
        from reportlab.lib.enums import TA_LEFT, TA_CENTER

        # Unique filename
        timestamp = int(time.time())
        safe_title = "".join(c for c in title if c.isalnum() or c in " _-").strip().replace(" ", "_")[:40]
        filename = f"{safe_title}_{timestamp}.pdf"
        filepath = PDF_DIR / filename

        doc = SimpleDocTemplate(
            str(filepath),
            pagesize=A4,
            leftMargin=2.5 * cm,
            rightMargin=2.5 * cm,
            topMargin=2.5 * cm,
            bottomMargin=2.5 * cm,
        )

        styles = getSampleStyleSheet()
        accent = HexColor("#00C6FF")
        dark = HexColor("#0a0a0a")

        title_style = ParagraphStyle(
            "CustomTitle",
            parent=styles["Heading1"],
            fontSize=20,
            textColor=accent,
            spaceAfter=6,
            alignment=TA_LEFT,
            fontName="Helvetica-Bold",
        )
        body_style = ParagraphStyle(
            "CustomBody",
            parent=styles["Normal"],
            fontSize=11,
            leading=16,
            textColor=dark,
            spaceAfter=8,
        )
        footer_style = ParagraphStyle(
            "Footer",
            parent=styles["Normal"],
            fontSize=8,
            textColor=HexColor("#888888"),
            alignment=TA_CENTER,
        )

        story = []
        story.append(Paragraph(title, title_style))
        story.append(HRFlowable(width="100%", thickness=1, color=accent, spaceAfter=12))
        story.append(Spacer(1, 0.3 * cm))

        # Split content by newlines and render each paragraph
        for line in content.split("\n"):
            line = line.strip()
            if line:
                # Escape any HTML-like chars for reportlab
                line = line.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
                story.append(Paragraph(line, body_style))
            else:
                story.append(Spacer(1, 0.2 * cm))

        story.append(Spacer(1, 1 * cm))
        story.append(HRFlowable(width="100%", thickness=0.5, color=HexColor("#cccccc"), spaceAfter=6))
        story.append(Paragraph("Generated by IN NET CREATION — Created by Manohar_S", footer_style))

        doc.build(story)

        # Return structured payload for frontend
        payload = {
            "type": "file",
            "url": f"/api/files/{filename}",
            "filename": filename,
            "mime": "application/pdf",
            "text": f"PDF generated: **{title}**. Click the Download button to save it."
        }
        return json.dumps(payload)

    except ImportError:
        logger.error("reportlab library missing")
        return json.dumps({
            "type": "error",
            "text": "PDF generation requires the 'reportlab' package. Please run: pip install reportlab"
        })
    except Exception as e:
        logger.exception(f"Failed to generate PDF: {e}")
        return json.dumps({
            "type": "error",
            "text": f"Failed to generate PDF: {str(e)}"
        })
